export const QUEUES = {
  NEW_SALES_ORDER: 'NEW_SALES_ORDER',
  REQUEST_DISPATCH_ORDER: 'REQUEST_DISPATCH_ORDER',
  WAREHOUSE_DISPATCH_ORDER: 'WAREHOUSE_DISPATCH_ORDER',
  DISPATCH_FAILED: 'DISPATCH_FAILED'
};
